In [52]:
filepath1 = 'Dataset/epinion_preprocessed.csv'
import pandas as pd
df1 = pd.read_csv(filepath)

In [53]:
df1.head()

,item,paid,review,stars,time,user
0,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7
1,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h
2,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky
3,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7

In [54]:
filepath2 = 'Dataset/network_trust_preprocessed.csv'
df2 = pd.read_csv(filepath2)

In [55]:
df2.head()

           user1  trust        user2
0  lavenderfruit  trust   kristinafh
1      shippo225  trust      sallyg8
2      aryeh7000  trust      liteair
3       chiquita  trust   magenta321
4   jeffsullivan  trust  rpllingrock

In [56]:
result = pd.merge(df1, df2, how='left', left_on='user', right_on='user1')
result1 = pd.merge(df1, df2, how='left', left_on='user', right_on='user2')

In [57]:
result.head()

,item,paid,review,stars,time,user,user1,trust,user2
0,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7,NaN,NaN,NaN
1,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h,NaN,NaN,NaN
2,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky,NaN,NaN,NaN
3,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944,NaN,NaN,NaN
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cyndia

In [58]:
result1.head()

,item,paid,review,stars,time,user,user1,trust,user2
0,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7,NaN,NaN,NaN
1,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h,NaN,NaN,NaN
2,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky,NaN,NaN,NaN
3,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944,NaN,NaN,NaN
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,amyk49,trust,spongebag7

In [59]:
result = result.append(result1)

In [60]:
result.head(50)

,item,paid,review,stars,time,user,user1,trust,user2
0,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7,NaN,NaN,NaN
1,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h,NaN,NaN,NaN
2,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky,NaN,NaN,NaN
3,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944,NaN,NaN,NaN
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cyndia
5,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,amyk49
6,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,rated-r
7,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,trailhound
8,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,megugrrrl
9,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,jbrd
10,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,blindsider
11,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,franks989
12,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,bryan_carey
13,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,42english
14,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,melissasrn
15,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,lilvoyce
16,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,monnie1976
17,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,javelina
18,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,surferdude7
19,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,johnusmaximus1
20,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,gr8ful
21,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,bruguru
22,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,freak369
23,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,davidmanning
24,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,seacow
25,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,wsmunch
26,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,gooberpyle
27,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,chiminou
28,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,whisperscream
29,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,petey_2
30,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,don_krider
31,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,twix109
32,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cntaur5
33,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,rcaarmsc07
34,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,dr.p
35,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,tombarnes
36,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,teamfreak16
37,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,dlstewart
38,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,symbiosis
39,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,matta75
40,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,popsrocks
41,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,shaky_jake
42,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cyndicm
43,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,speeddemon531
44,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7,NaN,NaN,NaN
45,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h,NaN,NaN,NaN
46,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky,NaN,NaN,NaN
47,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944,NaN,NaN,NaN
48,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cyndia
49,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,amyk49

In [62]:
result.drop_duplicates(inplace = True)

In [63]:
result.count()

item      3388337
paid      3382151
review    3388337
stars     3388337
time      3388337
user      3387993
user1     3229911
trust     3229931
user2     3229375
dtype: int64

In [70]:
result['user2'].nunique()

36880

In [71]:
result['user1'].nunique()

36059

In [72]:
result['user'].nunique()

116259

In [78]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

result.dropna(subset=['user1', 'trust', 'user2'], inplace = True)

In [79]:
type(result)

pandas.core.frame.DataFrame

In [80]:
result.count()

item      3229355
paid      3223302
review    3229355
stars     3229355
time      3229355
user      3229355
user1     3229355
trust     3229355
user2     3229355
dtype: int64

In [81]:
result.head()

,item,paid,review,stars,time,user,user1,trust,user2
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,cyndia
5,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,amyk49
6,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,rated-r
7,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,trailhound
8,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trust,megugrrrl

In [82]:
result.to_csv('Dataset/epinion_network_trust.csv')

In [85]:
filepath3 = 'Dataset/network_trustedby_preprocessed.csv'
df3 = pd.read_csv(filepath3)

In [86]:
df3.head()

           user1  trustedby       user2
0  lavenderfruit  trustedby  kristinafh
1       Rosalyce  trustedby      cindee
2        Sharkie  trustedby      theeye
3       chiquita  trustedby  magenta321
4       ValerieG  trustedby   jabbrjwz2

In [87]:
result = pd.merge(df1, df3, how='left', left_on='user', right_on='user1')
result1 = pd.merge(df1, df3, how='left', left_on='user', right_on='user2')

In [88]:
result = result.append(result1)

In [89]:
result.head()

,item,paid,review,stars,time,user,user1,trustedby,user2
0,pr-Sony_KV_36FS12__Standard_Televisions,1199,well when i graduated from college it didnt ta...,5,1012262400,pyros7,NaN,NaN,NaN
1,Minolta_QMS_PagePro_1250E_Printers,260,i got this printer from minolta as a warranty ...,4,1027296000,fgb59h,NaN,NaN,NaN
2,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1800,although i love my vaio especially the gorgeou...,2,1201305600,bucho_ky,NaN,NaN,NaN
3,Sony_VAIO_PCG_K45_P4_538_3_2GHz_1MB_L2_533MHz_...,1000,this is my first laptop and i bought it about ...,4,1118016000,redp944,NaN,NaN,NaN
4,pr-Durabrand_CD-85_Personal_CD_Player,20,just recently my sony dej001 walkman died on m...,4,1149292800,spongebag7,spongebag7,trustedby,rcaarmsc07

In [90]:
result.drop_duplicates(inplace = True)

In [92]:
result.dropna(subset=['user1', 'trustedby', 'user2'], inplace = True)

In [93]:
result.to_csv('Dataset/epinion_network_trustedby.csv')